### ISSUE TITLE
关于3.5.6小节中的源代码

### ISSUE THREAD

**Issue by xuangu** [fanzhidongyzby/cit#1]
3.5.6小节中的源代码在两个分支中均没有找到。能否请作者重新上传一下相关代码。

**Comment by fanzhidongyzby** [comment]
书中存在github上没有的代码，主要是因为在成书过程中为了让讲解和描述更清楚，我根据已有的代码做了重新调整，因此会出现x86和arm分支以及书中代码三个版本的差异。因为精力所限导致不能重写一个完整版本一直是我的一个遗憾，对此我深表歉意。
我非常希望有志之士能重写一个完整版本来弥补此缺憾，如果现有代码中存在重大的错误，我也非常欢迎你提交PR帮我改进。
个人建议阅读该书时，以书中的源码为准，github上的代码仅作参考之用。虽然书中有不少YY出的代码，但是我相信认真的读者应该可以轻松理解其中的内容。如果你对书中代码存在不理解的地方，欢迎及时与我交流。
