### ISSUE TITLE
关于测试用例问题

### ISSUE THREAD

**Issue by sealindx** [fanzhidongyzby/cit#3]
你好，大神，在看书前，能先上多几个测试用例吗，只有一个 test.c，感觉还是不懂怎么用，对于变量赋个初值也会报错

**Comment by OneTrainee** [comment]
你好，请问 Linux支持什么版本，在Ubuntu18.04 x86版本下采用 g++ -5 编译成功，"./cit ./file/test.c test" 也成功，但运行 test 时却提示段错误，求解决。
